### ISSUE TITLE
Transaction.parquet is missing

### ISSUE THREAD

**Issue by denmase** [naenumtou/ifrs9#1]
Hi,

Thank you for this repository, it helps me a lot in learning  provisioning and python. However, the `transaction.parquet` which is referenced by some notebooks, is missing from the repository. If it's not a problem to you, could you please provide it?

Thanks in advance.

Regards,
Agung

**Comment by naenumtou** [comment]
data is NOT for public. Just to learn to logic behind the model.

**Comment by naenumtou** [comment]
data is NOT for public. Just to learn to logic behind the model.
